### ISSUE TITLE
todo for version 0.5.0

### ISSUE THREAD

**Issue by bengolder** [bengolder/binary-tree#1]
- [x] add comparator argument to the constructor
- [x] add `delete()` method
- [ ] make a basic visual demo with d3. 
- [ ] add performance tests
